### ISSUE TITLE
Needs more comments.

### ISSUE THREAD

**Issue by knbedgm** [RetroAsgardian/kittn#4]
Me no understand da code...

**Comment by RetroAsgardian** [comment]
Fixing that.

**Comment by RetroAsgardian** [comment]
Specifically, what don't you understand about it?

**Comment by RetroAsgardian** [comment]
NOTE: look at addjoincode and getclients first.

**Comment by RetroAsgardian** [comment]
sorry about the confusion, i should have added more comments but i didnt
